### ISSUE TITLE
QSPI times out on 32F769IDISCOVERY

### ISSUE THREAD

**Issue by Jookia** [STMicroelectronics/STM32CubeF7#52] opened 2021-10-07 14:42 UTC
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus).

**Describe the set-up**
 * The board (either ST RPN reference or your custom board).
 * IDE or at least the compiler and its version.

I'm using the 32F769IDISCOVERY board and upstream Mbed OS.

**Describe the bug**

The HAL_QSPI_Transmit sometimes times out instead of returning data.

**How To Reproduce**

I've listed details on how to reproduce this at https://github.com/ARMmbed/mbed-os/issues/15108 , the place I reported this issue to in the first place. In summary, it's just using the QSPIFBlockDevice on Mbed OS and running it until it fails.

**Additional context**

This bug is strikingly similar to https://github.com/STMicroelectronics/STM32CubeF7/issues/6 . So much so that the fix works too.

**Screenshots**

N/A

**Comment by RKOUSTM** [comment] 2021-10-19 08:38
Hi @Jookia,

Thank you for your report. This point will be forwarded to our development teams for analysis. We will be back to you as soon as we get feedback.

Thank you again for your report.

With regards,
Rihab

**Comment by RKOUSTM** [comment] 2021-12-15 15:53
Duplicate of  #6.

**Comment by RKOUSTM** [comment] 2021-12-15 15:55
Hi @Jookia, 

Thank you for your report. This duplicated issue will remain closed. The reported issue #6 will be kept open to track the point.

With regards,

**Closed** 2021-12-15 15:55 UTC
Labels: duplicate, help wanted, hal

**Comment by Jookia** [comment] 2023-03-10 10:18
I've opened another bug report at #82 since this is still active sadly.
